language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
script:
  - ant -lib lib/ant clone-htsjdk 
  - ant test
